#
# Copyright (c) 2026 Contributors to the Eclipse Foundation
# Copyright (c) 2022, 2024 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License v. 1.0, which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Clause
#

name: JAXWS RI

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test on JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    outputs:
      jdk: ${{ steps.build.outputs.jdk }}
    strategy:
      matrix:
        java_version: [ 17 ]

    steps:
      - name: Checkout for build
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java_version }}
          cache: maven
      - name: Cache OWASP Dependency-Check Data
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data/
          key: ${{ runner.os }}-dc-nvd-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-dc-nvd-
      - name: Verify
        id: build
        run: |
          cd jaxws-ri
          mvn -B -V -U -C -Poss-release,dependency-check clean verify -Dgpg.skip=true -Doss.disallow.snapshots=false -Dittest=true
          cd ..
          echo "jdk=${{ matrix.java_version }}" >> $GITHUB_OUTPUT
      - name: Upload binary image
        uses: actions/upload-artifact@v6
        if: success()
        with:
          name: binary
          path: jaxws-ri/bundles/jaxws-ri/target/jaxws-ri.zip

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        test_suite:
#          - IN_VM (runs as part of the build)
          - TOMCAT
    name: Tests ${{ matrix.test_suite }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ needs.build.outputs.jdk }}
      - name: Checkout tests
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download binaries
        uses: actions/download-artifact@v7
        with:
          name: binary
      - name: Test
        run: |
          export ROOT=`pwd`
          unzip -q -d image jaxws-ri.zip
          wget -q -O tomcat.zip https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.14/bin/apache-tomcat-10.1.14.zip
          unzip -q tomcat.zip
          cd jaxws-ri
          mvn -B -V -U -C -am clean verify -Poss-release -Dgpg.skip=true -Doss.disallow.snapshots=false -pl :jaxws-unit -Dtomcat.home=$ROOT/apache-tomcat-10.1.14 -Dws.transport=${{ matrix.test_suite }} -Dws.localImage=$ROOT/image
